services:
  my_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Fortrek.1
      MYSQL_DATABASE: empresa_db
    ports:
      - "3306:3306"
    volumes:
      - my_mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  my_mysql_data:
